### ISSUE TITLE
100μF buffer capacitor to SMD?

### ISSUE THREAD

**Issue by florianschmidt** [schumar/ESP_BaPoTeSta#24]
Check possible SMD capacitors

**Comment by mer-at** [comment]
those look quite cheap
http://tinyurl.com/jxrbo84

1206 SMD capacitor 100uf 
50 pieces for 4,16$ including shipping

**Comment by mer-at** [comment]
LP 2985 IM5-3,3 might be a good replacement for the voltage regulator?
1.0uA instead of 1.6uA standby current.
16V supply voltage instead of just 6V (4 normal AA Batteries already give me 6,57V)
reichelt got them for 47cent a piece

can be used with small ceramic capacitor as output cap.

**Comment by schumar** [comment]
The LP2985 is only rated for 150mA; but LP38691DT-3.3 looks interesting

**Comment by schumar** [comment]
Created #33 for the voltage regulator topic.
